version: 2

jobs:
  test:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Install dev dependencies
          command: pip install -r requirements-dev.txt
      - run:
          name: Install plugins dependencies
          command: pip install -r requirements-plugins.txt
      - run:
          name: Test
          command: pytest tests/

  docs-build:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements-dev.txt
      - run:
          name: Build docs
          command: sphinx-build ./docs/source docs/_build
      - persist_to_workspace:
          root: docs/_build
          paths: ["_build"]

  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: docs/_build
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@klukas.net"
            git config user.name "ci-build"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist docs/_build/html

workflows:
  version: 2
  build:
    jobs:
      - test
      - docs-build
      - docs-deploy:
          requires:
            - test
            - docs-build
          filters:
            branches:
              only: master
