version: 2

jobs:
  test:
    docker:
      - image: python:3.9
    steps:
      - checkout
      # ======================================================================
      # Install dependencies
      # ======================================================================
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Install dev dependencies
          command: pip install -r requirements-dev.txt
      - run:
          name: Install plugins dependencies
          command: pip install -r requirements-plugins.txt
      # ======================================================================
      # Run tests
      # ======================================================================
      - run:
          name: Test
          command: pytest tests/

  docs-build:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements-dev.txt
      - run:
          name: Build docs
          command: sphinx-build docs/source docs/_build
      - persist_to_workspace:
          root: docs/
          paths: ["_build"]

  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: docs/_build
      # ======================================================================
      # Install gh-pages node package
      # ======================================================================
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email ${GH_EMAIL}
            git config user.name ${GH_USER}
      # ======================================================================
      # Use ssh keys with read and write permissions
      # ======================================================================
      - add_ssh_keys:
          fingerprints:
            - ${DEPLOY_KEY_FINGERPRINT}
      - run:
          name: Deploy docs to gh-pages branch
          command: |
            gh-pages \
            --dotfiles --message "doc updates [skip ci]" \
            --dist docs/_build/* --dest .
      # ======================================================================
      # Disable default jekyll usage on github's pages
      # ======================================================================
      - run:
          name: gh-pages checkout
          command: |
            git checkout gh-pages
      # Create .nokeyll file in gh-branches root, required by
      # github pages configuration.
      - run:
          name: Disable jekyll builds
          command: touch ./.nojekyll
      # Add and commit file to git repository branch
      - run:
          name: commit .nojekyll to gh-pages branch
          command: |
            export COMMIT_MESSAGE=\"$(git log --format=oneline -1 --pretty=format:'%h - %B')\"
            echo $COMMIT_MESSAGE
            git add -fA
            git commit --allow-empty -m "$COMMIT_MESSAGE"
            git push -f origin gh-pages
            echo "Deployed successfully"

workflows:
  version: 2
  build:
    jobs:
      - test
      - docs-build
      - docs-deploy:
          requires:
            - docs-build
          filters:
            branches:
              only: master
