uses: alteryx
name: "alteryx_sample_date_trigger"
path: "C:\\Users\\gabri\\Documents\\repos\\workflower\\samples\\alteryx\\sample_combine_two_sheets.yxmd"
trigger: date
run_date: "2022-01-14 18:55:05"
