import os

TABLEAU_SERVER_URL = os.getenv("TABLEAU_SERVER_URL")
TABLEAU_TOKEN_NAME = os.getenv("TABLEAU_TOKEN_NAME")
TABLEAU_TOKEN_VALUE = os.getenv("TABLEAU_TOKEN_VALUE")
TABLEAU_SITE_ID = os.getenv("TABLEAU_SITE_ID")
